export const countries = [
  "USA",
  "Canada",
  "India",
  "Australia",
  "Germany",
  "United Kingdom",
  "France",
  "Japan",
  "China",
  "Brazil",
  "Russia",
  "South Africa",
  "Italy",
  "Spain",
  "Mexico",
  "Argentina",
  "Turkey",
  "Netherlands",
  "South Korea",
  "Saudi Arabia",
  "Indonesia",
  "Switzerland",
  "Sweden",
  "Norway",
  "Belgium",
  "Denmark",
  "Finland",
  "New Zealand",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Nigeria",
  "Egypt",
  "Kenya",
  "Israel",
  "United Arab Emirates",
  "Qatar",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Iran",
  "Iraq",
  "Afghanistan",
  "Ukraine",
  "Poland",
  "Portugal",
  "Greece",
  "Czech Republic",
  "Hungary",
  "Austria",
  "Ireland",
  "Iceland",
  "Luxembourg",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Ecuador",
  "Bolivia",
  "Uruguay",
  "Paraguay",
  "Costa Rica",
  "Panama",
  "Cuba",
  "Dominican Republic",
  "Haiti",
  "Jamaica",
  "Trinidad and Tobago",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Libya",
  "Ethiopia",
  "Tanzania",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  "Mozambique",
  "Botswana",
  "Namibia",
  "Angola",
  "Ghana",
  "Ivory Coast",
  "Senegal",
  "Cameroon",
  "Sudan",
  "Democratic Republic of the Congo",
  "Kazakhstan",
  "Uzbekistan",
  "Turkmenistan",
  "Azerbaijan",
  "Armenia",
  "Georgia",
  "Mongolia",
  "Myanmar",
  "Cambodia",
  "Laos",
  "North Korea",
  "Bhutan",
  "Maldives",
  "Seychelles",
  "Fiji",
  "Papua New Guinea",
  "Solomon Islands",
  "Vanuatu",
  "Samoa",
  "Tonga",
  "Micronesia",
  "Palau",
  "Marshall Islands",
  "Nauru",
  "Kiribati",
];
