function ComprehensiveUserGuide() {
  return (
    <div className="w-full md:w-[80%] mx-auto my-10 p-5 bg-gray-100 rounded-lg shadow-lg">
      <h2 className="text-2xl font-bold text-gray-700 mb-4">
        Comprehensive User Guide
      </h2>
      <div className="space-y-4">
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            1. Introduction to Carbon Footprint
          </h3>
          <p className="text-gray-600">
            A carbon footprint measures the total greenhouse gases (GHGs)
            generated by our actions. It is often measured in metric tons of
            carbon dioxide (CO<sub>2</sub>) per year. Key sources include energy use,
            transportation, and waste. Understanding and managing your carbon
            footprint can help you reduce your environmental impact.
          </p>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            2. How to Use the Carbon Footprint Calculator
          </h3>
          <ol className="list-decimal list-inside text-gray-600 space-y-2">
            <li>
              Select the type of calculator you want to use:
              <ul className="list-disc list-inside ml-4">
                <li>
                  <strong>Carbon Offset Calculator:</strong> Calculates the
                  emissions you need to offset based on your activities.
                </li>
                <li>
                  <strong>Emissions Calculator:</strong> Breaks down your total
                  emissions from various activities.
                </li>
              </ul>
            </li>
            <li>
              Enter values for each factor (Vehicle, Natural Gas, Electricity,
              Fuel Oil, Waste). Ensure accurate inputs to get the most precise
              results.
              <ul className="list-disc list-inside ml-4">
                <li>
                  <strong>Vehicle:</strong> Include annual miles driven and fuel
                  efficiency (MPG).
                </li>
                <li>
                  <strong>Natural Gas:</strong> Enter monthly natural gas usage
                  in cubic feet or kilowatt-hours.
                </li>
                <li>
                  <strong>Electricity:</strong> Input monthly electricity usage
                  in kilowatt-hours.
                </li>
                <li>
                  <strong>Fuel Oil:</strong> Specify fuel oil usage if
                  applicable.
                </li>
                <li>
                  <strong>Waste:</strong> Estimate your waste production, based
                  on the number of people in your household.
                </li>
              </ul>
            </li>
          </ol>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            3. Understanding the Emission Factors
          </h3>
          <p className="text-gray-600">
            Each factor (Vehicle, Natural Gas, Electricity, etc.) has a specific
            emission factor, which is used to calculate the CO<sub>2</sub> emissions based
            on your inputs.
          </p>
          <ul className="list-disc list-inside ml-4 text-gray-600 space-y-2">
            <li>
              <strong>Vehicle Emissions:</strong> Calculated based on the fuel
              efficiency and distance traveled.
            </li>
            <li>
              <strong>Natural Gas Emissions:</strong> Considered for heating and
              cooking, converted based on your usage.
            </li>
            <li>
              <strong>Electricity Emissions:</strong> Vary depending on the
              electricity source. Renewable energy sources have a lower emission
              factor compared to coal or gas.
            </li>
            <li>
              <strong>Fuel Oil Emissions:</strong> Common in regions using oil
              for heating. High emission factor due to its density and carbon
              content.
            </li>
            <li>
              <strong>Waste Emissions:</strong> Include CO<sub>2</sub> from decomposing
              organic matter in landfills.
            </li>
          </ul>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            4. Tips for Reducing Your Carbon Footprint
          </h3>
          <ul className="list-disc list-inside ml-4 text-gray-600 space-y-2">
            <li>
              <strong>Transportation:</strong> Opt for public transportation,
              biking, or walking. Consider carpooling or using electric
              vehicles. Reduce air travel where possible.
            </li>
            <li>
              <strong>Energy Consumption:</strong> Use energy-efficient
              appliances and LED lighting. Install a programmable thermostat to
              manage heating and cooling. Consider renewable energy options like
              solar or wind power.
            </li>
            <li>
              <strong>Waste Management:</strong> Reduce, reuse, and recycle
              materials to minimize waste. Compost organic waste to reduce
              methane emissions from landfills.
            </li>
          </ul>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            5. Offsetting Your Carbon Footprint
          </h3>
          <p className="text-gray-600">
            After calculating your total emissions, you can offset them by
            investing in projects like:
          </p>
          <ul className="list-disc list-inside ml-4 text-gray-600 space-y-2">
            <li>Reforestation and afforestation projects.</li>
            <li>Renewable energy projects (solar, wind).</li>
            <li>Methane capture and utilization projects.</li>
          </ul>
          <p className="text-gray-600">
            Use the calculator to estimate the cost of offsetting your
            emissions. The cost is calculated based on the total CO<sub>2</sub> produced
            and the price per ton of carbon offsets.
          </p>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            6. Frequently Asked Questions (FAQs)
          </h3>
          <ul className="list-disc list-inside ml-4 text-gray-600 space-y-2">
            <li>
              <strong>How accurate is the calculator?</strong> The calculator
              provides estimates based on average emission factors. Actual
              emissions may vary depending on specific factors like energy
              source, vehicle efficiency, and more.
            </li>
            <li>
              <strong>Can I save my data and use it later?</strong> Yes, the
              calculator saves data locally in your browser storage. Make sure
              to keep your data private and secure.
            </li>
            <li>
              <strong>What is a carbon offset?</strong> A carbon offset is a
              reduction in GHG emissions made to compensate for emissions
              produced elsewhere. Offsetting can be done through various
              environmental projects.
            </li>
          </ul>
        </section>
        <section>
          <h3 className="text-lg font-semibold text-gray-700">
            7. Final Steps
          </h3>
          <p className="text-gray-600">
            After reviewing your total emissions, you can take action by
            reducing your footprint and considering offset options. Track your
            progress and revisit the calculator regularly to update your data
            and see improvements.
          </p>
        </section>
      </div>
    </div>
  );
}

export default ComprehensiveUserGuide;
